### ISSUE TITLE
Make emulateapj obsolete

### ISSUE THREAD

**Issue by jradavenport** [AASJournals/AASTeX52#1]
I always draft my papers using emulateapj because it most closely recreates what I would read in the actual journal.

This should be easy\* to make obsolete by releasing the actual ApJ template.

**Comment by augustfly** [comment]
Our plan for AASTeX TNG is make the default PDF compilation match the final ApJ template as closely as possible. There are lots of reasons for this, which you might guess:
- referees really want this version bc it is so much  easier to read;
- it transfers the authors layout requests to IOP project better than any Readme file could;
- it normalizes preprint version look and feel for everyone.

**Comment by augustfly** [comment]
The new version of [AASTeX (v6.0)](https://github.com/AASJournals/AASTeX60) was built off of emulateapj with permission of the authors/maintainers.   I'd like to consider this request closed, @jradavenport

**Comment by jradavenport** [comment]
Agreed! Awesome!
